name: BTNSIM CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  docker-build-and-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t btnsim-ci .

      - name: Run tests inside container
        run: |
          docker run --rm btnsim-ci